# Generated by Django 3.1 on 2020-11-26 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustedDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_index', models.CharField(max_length=50)),
                ('observation_date', models.DateField()),
                ('pin', models.CharField(max_length=20)),
                ('adjusted_ht_diff', models.FloatField(null=True)),
                ('observed_ht_diff', models.FloatField(null=True)),
                ('residuals', models.FloatField(null=True)),
                ('standard_deviation', models.FloatField(null=True)),
                ('std_dev_residual', models.FloatField(null=True)),
                ('standard_residual', models.FloatField(null=True)),
            ],
            options={
                'ordering': ['observation_date'],
            },
        ),
        migrations.CreateModel(
            name='HeightDifferenceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_index', models.CharField(max_length=50)),
                ('observation_date', models.DateField()),
                ('pin', models.CharField(max_length=20)),
                ('adjusted_ht_diff', models.FloatField(null=True)),
                ('uncertainty', models.FloatField(null=True)),
                ('observation_count', models.FloatField(null=True)),
            ],
            options={
                'ordering': ['observation_date'],
            },
        ),
        migrations.CreateModel(
            name='RangeParameters',
            fields=[
                ('pin', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Jan', models.FloatField(null=True)),
                ('Feb', models.FloatField(null=True)),
                ('Mar', models.FloatField(null=True)),
                ('Apr', models.FloatField(null=True)),
                ('May', models.FloatField(null=True)),
                ('Jun', models.FloatField(null=True)),
                ('Jul', models.FloatField(null=True)),
                ('Aug', models.FloatField(null=True)),
                ('Sep', models.FloatField(null=True)),
                ('Oct', models.FloatField(null=True)),
                ('Nov', models.FloatField(null=True)),
                ('Dec', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_number', models.CharField(max_length=20)),
                ('observation_date', models.DateField()),
                ('obs_set', models.IntegerField(null=True)),
                ('pin', models.CharField(max_length=20)),
                ('temperature', models.FloatField(null=True)),
                ('frm_pin', models.FloatField(null=True)),
                ('to_pin', models.FloatField(null=True)),
                ('standard_deviation', models.FloatField(null=True)),
                ('observed_ht_diff', models.FloatField(null=True)),
                ('corrected_ht_diff', models.FloatField(null=True)),
                ('update_index', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['observation_date'],
            },
        ),
        migrations.CreateModel(
            name='Calibration_Update',
            fields=[
                ('observation_date', models.DateField()),
                ('update_table', models.BooleanField(blank=True, null=True)),
                ('update_index', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('level_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staffs.digitallevel')),
                ('staff_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staffs.staff')),
                ('surveyor', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['observation_date'],
            },
        ),
        migrations.AddIndex(
            model_name='calibration_update',
            index=models.Index(fields=['update_index'], name='range_calib_update__74e358_idx'),
        ),
    ]
