# Generated by Django 3.1 on 2020-11-10 00:11

from __future__ import unicode_literals

from django.db import migrations, models
import csv
from datetime import datetime


def load_initial_data(apps, schema_editor):
	Authority = apps.get_model("accounts", "Authority")
	with open("assets/authority/authority_names.csv", 'r') as f:
		reader = csv.reader(f)
		header = next(reader)

		authoritys = []
		for row in reader:
			authority = Authority.objects.create(authority_abbrev = row[0], authority_name = row[1])
			#print(authority)

def reverse_func(apps, schema_editor):
	Authority = apps.get_model("accounts", Authority)

	Authority.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
    	migrations.RunPython(load_initial_data, reverse_func),
    ]
