# Generated by Django 3.1 on 2020-11-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_auto_20201112_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='calibration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='correction_factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='standard_temperature',
            field=models.FloatField(default=25.0),
        ),
    ]
