# Generated by Django 3.1 on 2021-02-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0004_auto_20210223_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftype',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='stafftype',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
