# Generated by Django 3.1 on 2022-06-09 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_group'),
        ('staffs', '0005_auto_20210223_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitallevel',
            name='level_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.authority'),
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.authority'),
        ),
    ]
