# Generated by Django 3.1 on 2020-11-26 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='uRawDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_number', models.CharField(max_length=20)),
                ('calibration_date', models.DateField()),
                ('pin_number', models.IntegerField(null=True)),
                ('staff_reading', models.FloatField(null=True)),
                ('number_of_readings', models.IntegerField(null=True)),
                ('standard_deviations', models.FloatField(null=True)),
                ('update_index', models.CharField(max_length=50)),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['calibration_date'],
            },
        ),
        migrations.CreateModel(
            name='uCalibrationUpdate',
            fields=[
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('calibration_date', models.DateField()),
                ('processed_date', models.DateTimeField()),
                ('correction_factor', models.FloatField()),
                ('observed_temperature', models.FloatField()),
                ('correction_factor_temperature', models.FloatField()),
                ('update_index', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('level_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staffs.digitallevel')),
                ('staff_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staffs.staff')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-calibration_date'],
            },
        ),
        migrations.AddIndex(
            model_name='urawdatamodel',
            index=models.Index(fields=['update_index'], name='staff_calib_update__8a7f27_idx'),
        ),
        migrations.AddIndex(
            model_name='ucalibrationupdate',
            index=models.Index(fields=['update_index'], name='staff_calib_update__52a5a6_idx'),
        ),
    ]
