# Generated by Django 3.1 on 2021-02-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_calibration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucalibrationupdate',
            name='observer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
