# Generated by Django 4.0.6 on 2022-09-16 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_calibration', '0002_ucalibrationupdate_observer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urawdatamodel',
            options={'ordering': ['-calibration_date', 'pin_number']},
        ),
    ]
